### ISSUE TITLE
SPPClient Project

### ISSUE THREAD

**Issue by acch** [CristieNordic/SPP_Restapi#1]
Hi there,

I hope all is well. Just wanted to make sure that you're aware of the [sppclient](https://github.com/sppautomation/sppclient) project - not sure if it already satisfies your needs. One of my colleagues has recently contributed some code and also wrote a nice [blog post](https://www.ibm.com/developerworks/community/blogs/storageneers/entry/SPP_RestAPI_Basics).

Keep it up - all the best!

Regards,
Achim

**Comment by Issen007** [comment]
Hi Achim,
Have you start working with SPP also and not only Spectrum Scale.  👍 

Interesting project with SPP Client, but this is just a test project and see what you can do with the Restful API.
I have a total different ideas for the API but that is great Blog post on IBM Website. 

Thanks
Christian

**Comment by acch** [comment]
I'm still mainly involved in Spectrum Scale - don't worry ;-) But whenever a colleague of mine publishes something on GitHub I stand on the sidelines and cheer :tada:

Just wanted you to avoid any double efforts...

Cheers and all the best!
Achim
